# Use official lightweight Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Expose a port (Render requirement)
EXPOSE 8080

# Run the bot continuously
CMD ["python", "Stock_Auto.py"]
